name: API testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        mariadb-version: [11.4]

    steps:
    - name: Git checkout
      uses: actions/checkout@v4

    - name: Install Node JS ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - uses: ankane/setup-mariadb@v1
      with:
        mariadb-version: ${{ matrix.mariadb-version }}

    - name: Clone Koller-Database
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        depth: 1
        branch: 'master'
        owner: 'KollerSystems'
        repository: 'Koller-Database'

    - name: Set up the database
      run: |
        cd Koller-Database
        sudo mariadb < schema.sql
        sudo mariadb kollegium < config.sql
        sudo mariadb kollegium < testdata.sql

    - name: Install project dependencies
      run: npm install

    - name: Run tests
      run: |
        sudo node index.js &
        sleep 2
        npm test
        sudo kill -9 `sudo lsof -i TCP:80 -t`